python bqskit/shuttling/qccd/QCCDSim/run.py "QAOA_16_compiled" "H" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QuantumVolume_16" "H" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QFT_16_compiled" "H" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "TFIM_n16_s100_compiled" "H" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "TFXY_n16_s100_compiled" "H" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QAOA_20_compiled" "H" "6" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QuantumVolume_20" "H" "6" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QFT_20_compiled" "H" "6" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"

python bqskit/shuttling/qccd/QCCDSim/run.py "QAOA_16_compiled" "G2x3" "4" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QuantumVolume_16" "G2x3" "4" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QFT_16_compiled" "G2x3" "4" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "TFIM_n16_s100_compiled" "G2x3" "4" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "TFXY_n16_s100_compiled" "G2x3" "4" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QAOA_20_compiled" "G2x3" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QuantumVolume_20" "G2x3" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"
python bqskit/shuttling/qccd/QCCDSim/run.py "QFT_20_compiled" "G2x3" "5" "Greedy" "Naive" "1" "0" "0" "FM" "GateSwap"